### ISSUE TITLE
Use VSCode's storage API to persist cache over reloads

### ISSUE THREAD

**Issue by jasonwilliams** [gilmoreorless/vscode-zoneinfo#6]
Closing then re-opening this can be intensive as i think it does a full re-index each time.

Can the cache be serialised then stored?
https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage

**Comment by gilmoreorless** [comment]
Thanks for the link! (And thanks also for actually using the extension.)

The extension APIs have come a long way since I first wrote this. I've been meaning to make use of some of the new APIs for a while, but frankly just never got around to it. This issue might give me the impetus to actually do something! 😆

**Comment by jasonwilliams** [comment]
No problem, I’ve been using it for work on temporal https://github.com/tc39/proposal-temporal. 

You should opt into hacktoberfest, maybe some of these issues get picked up.

**Comment by gilmoreorless** [comment]
Quick update: I've been looking into the parsing/cache performance, and the storage APIs you linked to. Using the VS Code storage to cache symbols across sessions will definitely improve loading speed, but also bring a new problem I haven't got a great solution to yet — cache invalidation. Sometimes it will need to re-parse the whole workspace (e.g. after a `git pull`), but knowing when to do that is… tricky. Especially if the files have changed in between VS Code sessions. _(Something something only two hard problems 😉)_

Some interesting findings:

1. Parsing the workspace as soon as the extension is activated (the current behaviour) is the worst time to do that. If the extension is activated at the same time the workspace is opened, it's competing with all the other extensions for CPU cycles. Doing something like waiting until the first user action is performed can make parsing the workspace 2-3 times faster.
2. The slowest part of parsing the workspace files is the I/O of asking VS Code to open the document for reading, before any content parsing can happen. Just getting access to each document is an order of magnitude slower than parsing its contents to find all the symbols. That blew away my idea of using content hashes for cache invalidation.

Making tweaks to the parsing, and using the VS Code storage APIs, will definitely make this extension less process-intensive. Once I've got a decent solution to the cache invalidation problem I'll make the changes.

**Comment by jasonwilliams** [comment]
I think I’ve seen other extensions use the file modification time as a cache invalidator. When you store the data you can also store the modification time for each file then only re-index that file if the time is higher. 
This should help with both git and “outside of VSCode” modifications.

I think there’s an unload or disactivate event when VSCode closes or you move to another workspace, you could write back to the storage api at that point.

**Comment by gilmoreorless** [comment]
Thanks, I'll give that a go. Hopefully the `fs.stat()` call isn't as sluggish as getting the contents.

**Comment by gilmoreorless** [comment]
I've released version 3.0.0 containing a revamp of the caching. It lazy-loads the parsing of symbols as needed:

* Parse only the active document when one is opened.
* Parse all relevant files in the same folder only after "Go to definition" or "Go to reference" is selected.
* Parse all relevant files in a multi-root workspace only after "Go to symbol in workspace" is selected.

Not doing the parsing of a full workspace on startup saves a significant amount of time and CPU. The cache is still in-memory only at the moment, but using the file content hash as the cache invalidation check. Since that's not what you suggested in this issue, I'll explain why:

1. Using the content hash instead of file modification time allows me to correctly provide symbols for open files that have been edited but not saved. VS Code keeps the contents of active documents in memory, allowing me to do cache checks without hitting the filesystem.
2. When getting all files in a folder to parse them, calling `workspace.openTextDocument()` on each one takes the longest time, as I mentioned earlier. However, calling `fs.stat()` on each file to get the modification time isn't much better. And if a file _has_ been modified, it still needs to be opened for parsing anyway.
3. Storing the cache inside VS Code's storage API brings some extra problems:
    1. The storage APIs can only store plain JSON-ish data. That means I'll need an extra serialise/deserialise step for the custom `ZoneSymbol` class every time the cache is accessed.
    2. As discussed before, cache invalidation becomes harder across sessions. If the extension is activated, and there are cached items in storage, how can I check that they're still valid? I'd need to run a check against each file, which brings back point 2 above — the filesystem is the bottleneck.
    3. Strangely, it doesn't look like you can actually remove an entry from the storage APIs. Only `.get()` and `.update()` are available.

Try out the latest version and let me know if the performance gains are acceptable for now. I'm willing to use the storage APIs if they bring a large benefit. But from what I've seen so far, I think the difference is negligible.

**Comment by jasonwilliams** [comment]
Thanks @gilmoreorless!
Looks like a great release, it seems to be much better.

**Comment by gilmoreorless** [comment]
I'm closing this issue because the startup performance has been improved, even if it wasn't in the originally-suggested way. Thanks for the feedback. 😄
